#ifndef lib_hpp
#define lib_hpp
#include <iostream>
#include <iomanip>
#include <stdio.h>
#include <stdlib.h>
#include <time.h>
#include <vector>
#include <sstream>
#include <string>
#include <random>
#include <ctype.h>
#include <algorithm> 
#include <fstream>
#include <chrono>
#include "RandInt.hpp"

using std::cout;
using std::cin;
using std::string;
using std::endl;
using std::vector;
using std::sort;
using std::ifstream;
using std::ofstream;
using std::setw;
using std::fixed;
using std::setprecision;
using std::stringstream;
#endif